var classes = [
    {
        "name": "App\\CacheKernel",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\HttpCache\\HttpCache",
            "Symfony\\Component\\HttpKernel\\Kernel",
            "parent"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\HttpCache\\HttpCache"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 3,
        "volume": 9.51,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 10,
        "lloc": 10,
        "mi": 71.2,
        "mIwoC": 71.2,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.2,
        "totalSystemComplexity": 16.2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\ProductController",
        "interface": false,
        "methods": [
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "list",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "FOS\\RestBundle\\Controller\\FOSRestController",
            "App\\Entity\\Product",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\ParamConverter",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Cache",
            "Nelmio\\ApiDocBundle\\Annotation",
            "FOS\\RestBundle\\Request\\ParamFetcher",
            "Symfony\\Component\\HttpFoundation\\Request",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Cache",
            "Nelmio\\ApiDocBundle\\Annotation"
        ],
        "parents": [
            "FOS\\RestBundle\\Controller\\FOSRestController"
        ],
        "lcom": 2,
        "length": 15,
        "vocabulary": 9,
        "volume": 47.55,
        "difficulty": 0.81,
        "effort": 38.63,
        "level": 1.23,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 58.52,
        "number_operators": 2,
        "number_operands": 13,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 78,
        "loc": 90,
        "lloc": 12,
        "mi": 114.17,
        "mIwoC": 64.58,
        "commentWeight": 49.59,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 25.58,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1.17,
        "totalSystemComplexity": 51.17,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controller\\UserController",
        "interface": false,
        "methods": [
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "list",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "FOS\\RestBundle\\Controller\\FOSRestController",
            "App\\Entity\\User",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\ParamConverter",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Cache",
            "Nelmio\\ApiDocBundle\\Annotation",
            "FOS\\RestBundle\\Request\\ParamFetcher",
            "Symfony\\Component\\HttpFoundation\\Request",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "FOS\\RestBundle\\Controller\\Annotations",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Cache",
            "Nelmio\\ApiDocBundle\\Annotation",
            "App\\Entity\\User",
            "Symfony\\Component\\Validator\\ConstraintViolationListInterface",
            "Symfony\\Component\\HttpFoundation\\Request",
            "FOS\\RestBundle\\Controller\\Annotations",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\ParamConverter",
            "Nelmio\\ApiDocBundle\\Annotation",
            "App\\Entity\\User",
            "DateTime",
            "Symfony\\Component\\HttpFoundation\\Response",
            "FOS\\RestBundle\\Controller\\Annotations",
            "Nelmio\\ApiDocBundle\\Annotation"
        ],
        "parents": [
            "FOS\\RestBundle\\Controller\\FOSRestController"
        ],
        "lcom": 2,
        "length": 54,
        "vocabulary": 17,
        "volume": 220.72,
        "difficulty": 4.82,
        "effort": 1064.2,
        "level": 0.21,
        "bugs": 0.07,
        "time": 59,
        "intelligentContent": 45.78,
        "number_operators": 9,
        "number_operands": 45,
        "number_operators_unique": 3,
        "number_operands_unique": 14,
        "cloc": 150,
        "loc": 183,
        "lloc": 33,
        "mi": 99.35,
        "mIwoC": 50.06,
        "commentWeight": 49.29,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 225.42,
        "totalStructuralComplexity": 900,
        "totalDataComplexity": 1.69,
        "totalSystemComplexity": 901.69,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Converter\\UserConverter",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Sensio\\Bundle\\FrameworkExtraBundle\\Request\\ParamConverter\\ParamConverterInterface",
            "Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface",
            "Doctrine\\ORM\\EntityManagerInterface",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\ParamConverter",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\ParamConverter",
            "LogicException",
            "LogicException",
            "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
            "Symfony\\Component\\HttpKernel\\Exception\\GoneHttpException"
        ],
        "parents": [],
        "lcom": 2,
        "length": 56,
        "vocabulary": 21,
        "volume": 245.97,
        "difficulty": 6.09,
        "effort": 1498.88,
        "level": 0.16,
        "bugs": 0.08,
        "time": 83,
        "intelligentContent": 40.36,
        "number_operators": 17,
        "number_operands": 39,
        "number_operators_unique": 5,
        "number_operands_unique": 16,
        "cloc": 14,
        "loc": 50,
        "lloc": 36,
        "mi": 85.32,
        "mIwoC": 48.77,
        "commentWeight": 36.55,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 81.27,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 0.8,
        "totalSystemComplexity": 243.8,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\DataFixtures\\Fixtures",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 8,
        "ccnMethodMax": 8,
        "externals": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture",
            "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface",
            "Doctrine\\Common\\Persistence\\ObjectManager",
            "App\\Entity\\Feature",
            "App\\Entity\\Product",
            "App\\Entity\\Image",
            "App\\Entity\\ProductFeature",
            "App\\Entity\\Client",
            "App\\Entity\\User",
            "DateTime"
        ],
        "parents": [
            "Doctrine\\Bundle\\FixturesBundle\\Fixture"
        ],
        "lcom": 1,
        "length": 274,
        "vocabulary": 168,
        "volume": 2025.49,
        "difficulty": 3.18,
        "effort": 6447,
        "level": 0.31,
        "bugs": 0.68,
        "time": 358,
        "intelligentContent": 636.36,
        "number_operators": 13,
        "number_operands": 261,
        "number_operators_unique": 4,
        "number_operands_unique": 164,
        "cloc": 6,
        "loc": 67,
        "lloc": 61,
        "mi": 59.19,
        "mIwoC": 36.83,
        "commentWeight": 22.36,
        "kanDefect": 1.37,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.05,
        "relativeSystemComplexity": 361.05,
        "totalStructuralComplexity": 722,
        "totalDataComplexity": 0.1,
        "totalSystemComplexity": 722.1,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Client",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCompany",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCompany",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsername",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUsername",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPassword",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSalt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "eraseCredentials",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 14,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Security\\Core\\User\\UserInterface",
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "App\\Entity\\Client",
            "App\\Entity\\Client",
            "App\\Entity\\Client",
            "Doctrine\\Common\\Collections\\Collection",
            "App\\Entity\\Client",
            "App\\Entity\\User",
            "App\\Entity\\Client",
            "App\\Entity\\User"
        ],
        "parents": [],
        "lcom": 4,
        "length": 49,
        "vocabulary": 9,
        "volume": 155.33,
        "difficulty": 7.75,
        "effort": 1203.78,
        "level": 0.13,
        "bugs": 0.05,
        "time": 67,
        "intelligentContent": 20.04,
        "number_operators": 18,
        "number_operands": 31,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 78,
        "loc": 150,
        "lloc": 72,
        "mi": 88.81,
        "mIwoC": 43.87,
        "commentWeight": 44.94,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 3.09,
        "relativeSystemComplexity": 12.09,
        "totalStructuralComplexity": 126,
        "totalDataComplexity": 43.25,
        "totalSystemComplexity": 169.25,
        "pageRank": 0.03,
        "afferentCoupling": 5,
        "efferentCoupling": 6,
        "instability": 0.55,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Feature",
        "interface": false,
        "methods": [
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Entity\\Feature"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 4,
        "volume": 20,
        "difficulty": 3,
        "effort": 60,
        "level": 0.33,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 6.67,
        "number_operators": 4,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 26,
        "loc": 45,
        "lloc": 19,
        "mi": 109.04,
        "mIwoC": 62.86,
        "commentWeight": 46.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.33,
        "relativeSystemComplexity": 3.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 10,
        "pageRank": 0.69,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Image",
        "interface": false,
        "methods": [
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUrl",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Entity\\Image",
            "App\\Entity\\Product",
            "App\\Entity\\Image",
            "App\\Entity\\Product",
            "JMS\\Serializer\\JsonSerializationVisitor",
            "JMS\\Serializer\\Annotation"
        ],
        "parents": [],
        "lcom": 1,
        "length": 22,
        "vocabulary": 6,
        "volume": 56.87,
        "difficulty": 3.5,
        "effort": 199.04,
        "level": 0.29,
        "bugs": 0.02,
        "time": 11,
        "intelligentContent": 16.25,
        "number_operators": 8,
        "number_operands": 14,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 44,
        "loc": 77,
        "lloc": 33,
        "mi": 100.51,
        "mIwoC": 54.45,
        "commentWeight": 46.06,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3.25,
        "relativeSystemComplexity": 4.25,
        "totalStructuralComplexity": 6,
        "totalDataComplexity": 19.5,
        "totalSystemComplexity": 25.5,
        "pageRank": 0.02,
        "afferentCoupling": 4,
        "efferentCoupling": 5,
        "instability": 0.56,
        "violations": {}
    },
    {
        "name": "App\\Entity\\Product",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDescription",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setDescription",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrice",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPrice",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTaxeRate",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTaxeRate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getImages",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addImage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeImage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProductFeatures",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addProductFeature",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeProductFeature",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 16,
        "nbMethods": 11,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 11,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "Doctrine\\Common\\Collections\\ArrayCollection",
            "App\\Entity\\Product",
            "App\\Entity\\Product",
            "App\\Entity\\Product",
            "App\\Entity\\Product",
            "Doctrine\\Common\\Collections\\Collection",
            "App\\Entity\\Product",
            "App\\Entity\\Image",
            "App\\Entity\\Product",
            "App\\Entity\\Image",
            "Doctrine\\Common\\Collections\\Collection",
            "App\\Entity\\Product",
            "App\\Entity\\ProductFeature",
            "App\\Entity\\Product",
            "App\\Entity\\ProductFeature"
        ],
        "parents": [],
        "lcom": 1,
        "length": 74,
        "vocabulary": 10,
        "volume": 245.82,
        "difficulty": 10.5,
        "effort": 2581.14,
        "level": 0.1,
        "bugs": 0.08,
        "time": 143,
        "intelligentContent": 23.41,
        "number_operators": 25,
        "number_operands": 49,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 146,
        "loc": 236,
        "lloc": 90,
        "mi": 87.16,
        "mIwoC": 40.23,
        "commentWeight": 46.93,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 3.88,
        "relativeSystemComplexity": 12.88,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 62,
        "totalSystemComplexity": 206,
        "pageRank": 0.04,
        "afferentCoupling": 6,
        "efferentCoupling": 6,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Entity\\ProductFeature",
        "interface": false,
        "methods": [
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFeature",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setFeature",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Entity\\ProductFeature",
            "App\\Entity\\Product",
            "App\\Entity\\ProductFeature",
            "App\\Entity\\Product",
            "App\\Entity\\Feature",
            "App\\Entity\\ProductFeature",
            "App\\Entity\\Feature",
            "JMS\\Serializer\\JsonSerializationVisitor",
            "JMS\\Serializer\\Annotation"
        ],
        "parents": [],
        "lcom": 1,
        "length": 30,
        "vocabulary": 7,
        "volume": 84.22,
        "difficulty": 3.8,
        "effort": 320.04,
        "level": 0.26,
        "bugs": 0.03,
        "time": 18,
        "intelligentContent": 22.16,
        "number_operators": 11,
        "number_operands": 19,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 72,
        "loc": 115,
        "lloc": 43,
        "mi": 97.81,
        "mIwoC": 50.75,
        "commentWeight": 47.05,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 2.13,
        "relativeSystemComplexity": 11.13,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 17,
        "totalSystemComplexity": 89,
        "pageRank": 0.02,
        "afferentCoupling": 4,
        "efferentCoupling": 6,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "App\\Entity\\User",
        "interface": false,
        "methods": [
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFirstname",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setFirstname",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLastname",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setLastname",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBirthDate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setBirthDate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDeletedAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setDeletedAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUpdatedAt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getClient",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setClient",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Entity\\User",
            "App\\Entity\\User",
            "DateTime",
            "App\\Entity\\User",
            "DateTime",
            "App\\Entity\\User",
            "DateTime",
            "DateTime",
            "App\\Entity\\Client",
            "App\\Entity\\Client",
            "DateTime",
            "Doctrine\\ORM\\Mapping",
            "Doctrine\\ORM\\Mapping"
        ],
        "parents": [],
        "lcom": 1,
        "length": 44,
        "vocabulary": 8,
        "volume": 132,
        "difficulty": 4.5,
        "effort": 594,
        "level": 0.22,
        "bugs": 0.04,
        "time": 33,
        "intelligentContent": 29.33,
        "number_operators": 17,
        "number_operands": 27,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 140,
        "loc": 207,
        "lloc": 67,
        "mi": 93,
        "mIwoC": 45.18,
        "commentWeight": 47.81,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 11.38,
        "relativeSystemComplexity": 11.38,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 148,
        "totalSystemComplexity": 148,
        "pageRank": 0.02,
        "afferentCoupling": 5,
        "efferentCoupling": 5,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\ExpressionLanguage\\CountExpression",
        "interface": false,
        "methods": [
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCompiler",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEvaluator",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContextVariables",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Hateoas\\Expression\\ExpressionFunctionInterface"
        ],
        "parents": [],
        "lcom": 4,
        "length": 18,
        "vocabulary": 7,
        "volume": 50.53,
        "difficulty": 2,
        "effort": 101.06,
        "level": 0.5,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 25.27,
        "number_operators": 8,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 12,
        "loc": 40,
        "lloc": 28,
        "mi": 93.88,
        "mIwoC": 56.37,
        "commentWeight": 37.52,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 7,
        "relativeSystemComplexity": 7,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 28,
        "totalSystemComplexity": 28,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Kernel",
        "interface": false,
        "methods": [
            {
                "name": "getCacheDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLogDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "registerBundles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureContainer",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Kernel",
            "Symfony\\Component\\DependencyInjection\\Compiler\\CompilerPassInterface",
            "class",
            "Symfony\\Component\\DependencyInjection\\ContainerBuilder",
            "Symfony\\Component\\Config\\Loader\\LoaderInterface",
            "Symfony\\Component\\Routing\\RouteCollectionBuilder",
            "Symfony\\Component\\DependencyInjection\\ContainerBuilder",
            "Symfony\\Component\\DependencyInjection\\Reference"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "lcom": 2,
        "length": 129,
        "vocabulary": 38,
        "volume": 676.98,
        "difficulty": 6.59,
        "effort": 4461.93,
        "level": 0.15,
        "bugs": 0.23,
        "time": 248,
        "intelligentContent": 102.71,
        "number_operators": 42,
        "number_operands": 87,
        "number_operators_unique": 5,
        "number_operands_unique": 33,
        "cloc": 7,
        "loc": 54,
        "lloc": 49,
        "mi": 68.83,
        "mIwoC": 42.37,
        "commentWeight": 26.46,
        "kanDefect": 0.89,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 49.33,
        "totalStructuralComplexity": 294,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 296,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Listener\\ExceptionListener",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addNormalizer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onKernelException",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "JMS\\Serializer\\Serializer",
            "App\\Normalizer\\AbstractNormalizer",
            "Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [],
        "lcom": 1,
        "length": 64,
        "vocabulary": 24,
        "volume": 293.44,
        "difficulty": 6.58,
        "effort": 1930.51,
        "level": 0.15,
        "bugs": 0.1,
        "time": 107,
        "intelligentContent": 44.6,
        "number_operators": 14,
        "number_operands": 50,
        "number_operators_unique": 5,
        "number_operands_unique": 19,
        "cloc": 12,
        "loc": 48,
        "lloc": 36,
        "mi": 83.21,
        "mIwoC": 48.24,
        "commentWeight": 34.97,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 81.2,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 243.6,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Listener\\PurgeListener",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "purge",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\DependencyInjection\\Container",
            "Symfony\\Component\\HttpKernel\\Event\\FilterResponseEvent"
        ],
        "parents": [],
        "lcom": 1,
        "length": 37,
        "vocabulary": 18,
        "volume": 154.29,
        "difficulty": 5.75,
        "effort": 887.15,
        "level": 0.17,
        "bugs": 0.05,
        "time": 49,
        "intelligentContent": 26.83,
        "number_operators": 14,
        "number_operands": 23,
        "number_operators_unique": 6,
        "number_operands_unique": 12,
        "cloc": 3,
        "loc": 20,
        "lloc": 17,
        "mi": 85.8,
        "mIwoC": 57.57,
        "commentWeight": 28.23,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.1,
        "relativeSystemComplexity": 81.1,
        "totalStructuralComplexity": 162,
        "totalDataComplexity": 0.2,
        "totalSystemComplexity": 162.2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Normalizer\\AbstractExceptionNormalizer",
        "interface": false,
        "methods": [
            {
                "name": "normalize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatusCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDefaultMessage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Normalizer\\AbstractNormalizer"
        ],
        "parents": [
            "App\\Normalizer\\AbstractNormalizer"
        ],
        "lcom": 1,
        "length": 22,
        "vocabulary": 15,
        "volume": 85.95,
        "difficulty": 2.91,
        "effort": 250.04,
        "level": 0.34,
        "bugs": 0.03,
        "time": 14,
        "intelligentContent": 29.55,
        "number_operators": 6,
        "number_operands": 16,
        "number_operators_unique": 4,
        "number_operands_unique": 11,
        "cloc": 9,
        "loc": 21,
        "lloc": 12,
        "mi": 105.23,
        "mIwoC": 62.78,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 9.33,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 28,
        "pageRank": 0.03,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Normalizer\\AbstractNormalizer",
        "interface": false,
        "methods": [
            {
                "name": "supports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHandledClasses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 2,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 2,
        "effort": 41.79,
        "level": 0.5,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 10.45,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 11,
        "loc": 26,
        "lloc": 15,
        "mi": 106.98,
        "mIwoC": 64.7,
        "commentWeight": 42.28,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 7,
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Normalizer\\BadRequestHttpNormalizer",
        "interface": false,
        "methods": [
            {
                "name": "getStatusCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDefaultMessage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHandledClasses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Normalizer\\AbstractExceptionNormalizer"
        ],
        "parents": [
            "App\\Normalizer\\AbstractExceptionNormalizer"
        ],
        "lcom": 3,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 0.5,
        "effort": 3.96,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15.85,
        "number_operators": 3,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 9,
        "loc": 28,
        "lloc": 19,
        "mi": 104.16,
        "mIwoC": 65.68,
        "commentWeight": 38.48,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Normalizer\\GoneHttpNormalizer",
        "interface": false,
        "methods": [
            {
                "name": "getStatusCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDefaultMessage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHandledClasses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Normalizer\\AbstractExceptionNormalizer"
        ],
        "parents": [
            "App\\Normalizer\\AbstractExceptionNormalizer"
        ],
        "lcom": 3,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 0.5,
        "effort": 3.96,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15.85,
        "number_operators": 3,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 9,
        "loc": 28,
        "lloc": 19,
        "mi": 104.16,
        "mIwoC": 65.68,
        "commentWeight": 38.48,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Normalizer\\NotFoundHttpNormalizer",
        "interface": false,
        "methods": [
            {
                "name": "getStatusCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDefaultMessage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHandledClasses",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Normalizer\\AbstractExceptionNormalizer"
        ],
        "parents": [
            "App\\Normalizer\\AbstractExceptionNormalizer"
        ],
        "lcom": 3,
        "length": 5,
        "vocabulary": 3,
        "volume": 7.92,
        "difficulty": 0.5,
        "effort": 3.96,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15.85,
        "number_operators": 3,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 9,
        "loc": 28,
        "lloc": 19,
        "mi": 104.16,
        "mIwoC": 65.68,
        "commentWeight": 38.48,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repository\\AbstractPaginatorRepository",
        "interface": false,
        "methods": [
            {
                "name": "paginate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Doctrine\\ORM\\EntityRepository",
            "Hateoas\\Representation\\PaginatedRepresentation",
            "Doctrine\\ORM\\QueryBuilder",
            "LogicException",
            "Pagerfanta\\Adapter\\DoctrineORMAdapter",
            "Pagerfanta\\Pagerfanta",
            "Hateoas\\Representation\\Factory\\PagerfantaFactory",
            "Hateoas\\Configuration\\Route"
        ],
        "parents": [
            "Doctrine\\ORM\\EntityRepository"
        ],
        "lcom": 1,
        "length": 24,
        "vocabulary": 13,
        "volume": 88.81,
        "difficulty": 5.63,
        "effort": 499.56,
        "level": 0.18,
        "bugs": 0.03,
        "time": 28,
        "intelligentContent": 15.79,
        "number_operators": 6,
        "number_operands": 18,
        "number_operators_unique": 5,
        "number_operands_unique": 8,
        "cloc": 8,
        "loc": 21,
        "lloc": 13,
        "mi": 102.64,
        "mIwoC": 61.79,
        "commentWeight": 40.85,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 10.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 10.5,
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 8,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "App\\Repository\\ProductRepository",
        "interface": false,
        "methods": [
            {
                "name": "findWithJoins",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Repository\\AbstractPaginatorRepository",
            "Hateoas\\Representation\\PaginatedRepresentation",
            "parent"
        ],
        "parents": [
            "App\\Repository\\AbstractPaginatorRepository"
        ],
        "lcom": 1,
        "length": 47,
        "vocabulary": 23,
        "volume": 212.61,
        "difficulty": 5.14,
        "effort": 1092.57,
        "level": 0.19,
        "bugs": 0.07,
        "time": 61,
        "intelligentContent": 41.37,
        "number_operators": 10,
        "number_operands": 37,
        "number_operators_unique": 5,
        "number_operands_unique": 18,
        "cloc": 11,
        "loc": 30,
        "lloc": 19,
        "mi": 95.86,
        "mIwoC": 55.54,
        "commentWeight": 40.32,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.41,
        "relativeSystemComplexity": 100.41,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 0.82,
        "totalSystemComplexity": 200.82,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repository\\UserRepository",
        "interface": false,
        "methods": [
            {
                "name": "getClientUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Repository\\AbstractPaginatorRepository",
            "App\\Entity\\Client",
            "Hateoas\\Representation\\PaginatedRepresentation",
            "App\\Entity\\Client",
            "parent"
        ],
        "parents": [
            "App\\Repository\\AbstractPaginatorRepository"
        ],
        "lcom": 1,
        "length": 59,
        "vocabulary": 29,
        "volume": 286.62,
        "difficulty": 5.21,
        "effort": 1492.82,
        "level": 0.19,
        "bugs": 0.1,
        "time": 83,
        "intelligentContent": 55.03,
        "number_operators": 9,
        "number_operands": 50,
        "number_operators_unique": 5,
        "number_operands_unique": 24,
        "cloc": 13,
        "loc": 32,
        "lloc": 19,
        "mi": 96.36,
        "mIwoC": 54.63,
        "commentWeight": 41.73,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 144.42,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 0.85,
        "totalSystemComplexity": 288.85,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    }
]